// 📁 /pages/offer1.js — Full Converted React Landing Page
import { useEffect } from 'react';
import Head from 'next/head';

export default function Offer1() {
  useEffect(() => {
    const alerts = [
      { name: 'Liam K.', amount: '$750' },
      { name: 'Jasmine R.', amount: '$825' },
      { name: 'Mike D.', amount: '$600' },
      { name: 'Tina W.', amount: '$1,000' },
      { name: 'Chris B.', amount: '$720' },
      { name: 'Sadie L.', amount: '$890' },
      { name: 'Olivia A.', amount: '$800' },
      { name: 'Kayla C.', amount: '$900' },
      { name: 'Peter P.', amount: '$620' },
    ];

    let current = 0;
    const alertBox = document.getElementById('nameAlert');
    const alertText = document.getElementById('alertText');

    function showAlert() {
      const alert = alerts[current];
      alertText.innerHTML = `<span class="name">${alert.name}</span> received ${alert.amount}!`;

      alertBox.classList.remove('fade-out', 'slide-in');
      void alertBox.offsetWidth;
      alertBox.classList.add('slide-in');

      setTimeout(() => {
        alertBox.classList.add('fade-out');
        alertBox.classList.remove('slide-in');
      }, 2000);

      current = (current + 1) % alerts.length;
    }

    showAlert();
    const interval = setInterval(showAlert, 3000);
    return () => clearInterval(interval);
  }, []);

  const handleClick = () => {
    window.location.href = 'https://glstrck.com/aff_c?offer_id=1615&aff_id=9398&source=1';
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Create Next App_files/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet" />
        <script src="/Create Next App_files/particles.min.js" async></script>
        <style>{`
          .notification {
            position: fixed;
            top: 20px;
            left: 50%;
            transform: translateX(-50%) translateY(-100%);
            background-color: #f5f5f5;
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 10px 16px;
            font-family: sans-serif;
            font-size: 14px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            z-index: 9999;
            opacity: 0;
            visibility: hidden;
            pointer-events: none;
            transition: transform 0.4s ease, opacity 0.4s ease, visibility 0s linear 0.4s;
            border-radius: 8px;
          }
          .notification.slide-in {
            transform: translateX(-50%) translateY(0%);
            opacity: 1;
            visibility: visible;
            pointer-events: auto;
            transition: transform 0.4s ease, opacity 0.4s ease, visibility 0s;
          }
          .notification.fade-out {
            opacity: 0;
            visibility: hidden;
            pointer-events: none;
            transition: transform 0.4s ease, opacity 0.4s ease, visibility 0s linear 0.4s;
          }
        `}</style>
      </Head>

      <div id="particles-js" style={{ position: 'fixed', width: '100%', height: '100%', zIndex: 1 }}></div>

      <div id="nameAlert" className="notification">
        <img src="/Create Next App_files/vlogo.png" width="35" height="35" alt="Venmo" />
        <div id="alertText">
          <span className="name">Liam K.</span> received $750!
        </div>
      </div>

      <div className="page-container">
        <div className="reward-card">
          <div className="venmo-logo-container">
            <img alt="Venmo" loading="lazy" width="100" height="100" className="venmo-logo" src="/Create Next App_files/vlogo(1).png" />
            <div className="cash-text">Venmo Balance</div>
            <img alt="Verified" loading="lazy" width="80" height="80" className="verd-logo" src="/Create Next App_files/verd.png" />
          </div>

          <div className="amount" id="amount">$750.00</div>
          <div className="amount-subtext">ready to transfer</div>

          <div className="instructions-container">
            <div className="instruction-item"><span className="number">1</span><span>Click the Button Below</span></div>
            <div className="instruction-item"><span className="number">2</span><span>Enter Your Venmo Info</span></div>
            <div className="instruction-item"><span className="number">3</span><span className="underline">Complete Quick Offers</span></div>
            <div className="instruction-item"><span className="number">4</span><span>Get Paid Instantly</span></div>
          </div>

          <div className="button-container">
            <button id="claimButton" className="claim-button" onClick={handleClick}>
              Get Your $750 →
            </button>
            <img alt="Trust Badge" loading="lazy" width="100" height="50" className="trust-badge" style={{ width: '100%', height: 'auto' }} src="/Create Next App_files/trus2.png" />
          </div>
        </div>
      </div>
    </>
  );
}
